[pre-commit]
parallel = true

[pre-commit.commands.prettier]
glob = "*.{json,json5,md,yml,yaml}"
run = "mise run format:check {staged_files}"

[pre-commit.commands.renovate-config-validator]
glob = "*.json5"
run = "mise run validate {staged_files}"
