[pre-commit]
parallel = true

[pre-commit.commands.prettier]
glob = "*.{json,json5}"
run = "prettier --check {staged_files}"

[pre-commit.commands.renovate-config-validator]
glob = "*.json5"
run = "renovate-config-validator --strict {staged_files}"

[pre-commit.commands.format-yaml]
run = "yamlfmt {staged_files}"
glob = ["*.yml", "*.yaml"]
stage_fixed = true

[pre-commit.commands.shellcheck]
glob = "*.sh"
run = "shellcheck {staged_files}"
